name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ðŸ”§ Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: ðŸšš Install dependencies
      run: dotnet restore

    - name: ðŸš€ Build
      run: dotnet build --configuration Debug --no-restore

    - name: ðŸ§ª Test
      run: dotnet test --no-restore --no-build --configuration Debug --logger:"liquid.md;LogFileName=TestReport.md;"

    - name: ðŸ’¾ Upload test report
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Test Results'
        path: ${{github.workspace}}/*.Tests/TestResults/TestReport.md
